# -*- coding: utf-8 -*-

# Created: Mon Mar 20 14:28:58 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(386, 722)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wg_main = QtGui.QWidget(Form)
        self.wg_main.setObjectName("wg_main")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wg_main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.wg_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(350, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_layers = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_layers.sizePolicy().hasHeightForWidth())
        self.lbl_layers.setSizePolicy(sizePolicy)
        self.lbl_layers.setObjectName("lbl_layers")
        self.horizontalLayout_2.addWidget(self.lbl_layers)
        self.cb_layers = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_layers.sizePolicy().hasHeightForWidth())
        self.cb_layers.setSizePolicy(sizePolicy)
        self.cb_layers.setMinimumSize(QtCore.QSize(100, 0))
        self.cb_layers.setObjectName("cb_layers")
        self.horizontalLayout_2.addWidget(self.cb_layers)
        self.lbl_aov = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_aov.sizePolicy().hasHeightForWidth())
        self.lbl_aov.setSizePolicy(sizePolicy)
        self.lbl_aov.setObjectName("lbl_aov")
        self.horizontalLayout_2.addWidget(self.lbl_aov)
        self.cb_AOV = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_AOV.sizePolicy().hasHeightForWidth())
        self.cb_AOV.setSizePolicy(sizePolicy)
        self.cb_AOV.setMinimumSize(QtCore.QSize(100, 0))
        self.cb_AOV.setObjectName("cb_AOV")
        self.horizontalLayout_2.addWidget(self.cb_AOV)
        self.verticalLayout_3.addWidget(self.frame)
        self.wgList = QtGui.QWidget(self.wg_main)
        self.wgList.setMinimumSize(QtCore.QSize(350, 0))
        self.wgList.setObjectName("wgList")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.wgList)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lyAovList = QtGui.QVBoxLayout()
        self.lyAovList.setObjectName("lyAovList")
        self.horizontalLayout_4.addLayout(self.lyAovList)
        self.verticalLayout_3.addWidget(self.wgList)
        self.grp_options = QtGui.QGroupBox(self.wg_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_options.sizePolicy().hasHeightForWidth())
        self.grp_options.setSizePolicy(sizePolicy)
        self.grp_options.setMinimumSize(QtCore.QSize(0, 50))
        self.grp_options.setTitle("")
        self.grp_options.setObjectName("grp_options")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.grp_options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ly_newId = QtGui.QHBoxLayout()
        self.ly_newId.setObjectName("ly_newId")
        self.le_idName = QtGui.QLineEdit(self.grp_options)
        self.le_idName.setObjectName("le_idName")
        self.ly_newId.addWidget(self.le_idName)
        self.btn_newId = QtGui.QPushButton(self.grp_options)
        self.btn_newId.setObjectName("btn_newId")
        self.ly_newId.addWidget(self.btn_newId)
        self.btn_refresh = QtGui.QPushButton(self.grp_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy)
        self.btn_refresh.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_refresh.setText("")
        self.btn_refresh.setObjectName("btn_refresh")
        self.ly_newId.addWidget(self.btn_refresh)
        self.verticalLayout_4.addLayout(self.ly_newId)
        self.verticalLayout_3.addWidget(self.grp_options)
        self.verticalLayout.addWidget(self.wg_main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "ID Manager Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_layers.setText(QtGui.QApplication.translate("Form", "Render Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_aov.setText(QtGui.QApplication.translate("Form", "AOV", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_newId.setText(QtGui.QApplication.translate("Form", "Create New ID AOV", None, QtGui.QApplication.UnicodeUTF8))

